### ISSUE TITLE
As a user, I want to be able to correct inaccurate metadata in the files I just uploaded

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#132]
## Description
Once I’ve uploaded session files, I want to know that the information was loaded into the system correctly and be able to make changes before saving tot the database.

## Acceptance criteria
- [x] System should automatically extract certain relevant metadata from the dataFrame or staging table and display them back to the user for confirmation:
  - [x] ~Collection date~ _Delegated to #208_ 
  - [x] ~Start time (defined as: earliest matched timestamp within a file pair)~ _Delegated to #208_
  - [x] Device make and model Issue #232 
  - [x] ~Pollutant and unit measure~(System current relies on at least one pollutant already existing in the database.)
- [x] Each input field is editable by user.
- [x] Selecting “Save”:
  - [x] Triggers the system to copy all data to main table. PR #226 
  - [x] Flushes all data from dataFrame/staging table. PR #226 
  - [x] Pushes user to View Map view (earliest session, if user has uploaded multiple sessions). Issue #159 
- [x] Selecting “Cancel”:
  - [x] Flushes all data from dataFrame/staging table. PR #226 
  - [x] Returns user to Add Data view. Issue #231 
- [ ] All open questions in Issue have been answered or moved into new Issues.

## Dependencies and assumptions
- Assumes upload flow has been implemented
- System will display dates and times in a 12-hour US format.
- Editing functionality and UI and will be inherited from identified design system (Semantic UI for the calendar component?).
- Requires a separate Issue for deleting/editing an entire data set or individual data points.
- View will be built in React

## Related documentation
Wireframes 
- [WOEIP Schema V2](https://user-images.githubusercontent.com/32755410/80738548-0cbd9780-8aca-11ea-9ea1-b612bfebb99f.png)

- [WOAQ-Upload-v5-Wireframes.pdf](https://github.com/openoakland/woeip/files/3937179/WOAQ-Upload-v5-Wireframes.pdf) (see page 9)
- [Wireframes Parent File](https://www.figma.com/file/IZw8VvX1CsRc764CTvg4aRSU/WOAQ-Wireframes-Parent-File?node-id=340%3A5671l) - going off of the "Upload Flow v5: Happy Path Prototype"

**Comment by TangoYankee** [comment]
> System should automatically extract certain relevant metadata from the dataFrame or staging table and display them back to the user for confirmation: 
- Delegated to issue #208

**Comment by TangoYankee** [comment]
As discussed in this [Slack Thread](https://app.slack.com/client/T02FEGG84/C95U7371C/thread/C95U7371C-1588203857.255500) (see [contributing doc](https://github.com/openoakland/woeip#contact) for authorization to view), the front end will be able to use [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) or another Object to fulfill these design requirements better than a [SQL Staging Table](https://www.quora.com/What-is-staging-table?share=1)

**Comment by theecrit** [comment]
> Delegated to issue #208

Updated issue description to reflect this.

**Comment by theecrit** [comment]
@Ajay-Vishwanath Can we safely close this now that #232 is closed?

**Comment by Ajay-Vishwanath** [comment]
> @Ajay-Vishwanath Can we safely close this now that #232 is closed?

@theecrit Yes! Sorry for the late reply but everything looks clear here.
