### ISSUE TITLE
Pre-launch checklist for live MVP

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#320]
## Description
In an effort to cross our t's and dot our i's, we'd like to develop an explicit checklist to guide the live rollout of our initial MVP. This should include two core sections:

1. Acceptance criteria for the system to go live
2. Steps to complete live launch

Below is an initial draft but it would be great for the team to refine as appropriate based on best practice for product launches. I've already reached out to the brigade network to see if any other brigades have something similar but it doesn't appear to be the case. So whatever we produce could conceivably be shared out with the national network, too. I'm sure there are similar checklists online in various product management/engineering circles we could borrow from...

### 1. Acceptance criteria for the system to go live
- [ ] All issues in [P1 MVP Project](https://github.com/openoakland/woeip/projects/5) marked complete.
- [ ] Each use case has been tested end-to-end for breaking bugs:
  - [ ] Single file upload
  - [ ] Matching file upload
  - [ ] Mismatching file upload
  - [ ] Duplicate file upload
  - [ ] Canceling upload
  - [ ] Saving upload (confirming session data)
  - [ ] Loading map view of color-coded data points according to specified rules (see #237)
  - [ ] Navigating on the map (moving up/down/left/right and zooming in/out)
  - [ ] Selecting and viewing data from a different date using the date picker
  - [ ] Downloading raw data files
  - [ ] Navigating to site sections via global nav menu
  - [ ] Viewing an About page that describes the project and teams
  - [ ] Copy has been proofread for typos, grammar, and clarity 
  - [ ] No broken links
- [ ] Deployment process (pushing `develop` to `main`) has been defined and documented in Github. (~@theecrit or @gsehrlich to add link to video instructions~)
- [ ] Project documentation is updated to enable new members to pick up as needed (including basic recommendations for providing Post-MVP issues).
- [ ] Post-live maintenance commitments are defined and documented
