### ISSUE TITLE
Backlog grooming/epic definition

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#373]
## Description

The project roadmap is currently captured in 3 projects:
- P1: MVP
- P2a: Post-MVP Enhancements
- P2b: Account Management (post-MVP)

The issues documented there are at different levels of depth and relationships/dependencies aren't obvious. Additionally, there are likely open issues that don't belong to a project board and may be easily overlooked. Finally, the P1, P2 & P3 project boards don't clearly correspond to active the active sprint board, so it's difficult to easily understand and track current project status.

### Acceptance criteria
- [ ] Definitions of "epic," "story," and "task" are documented somewhere logical for PMs.
- [ ] All open issues are rewritten to clearly correspond to an epic, story, or task.
- [ ] Dependencies between open issues are clearly tagged/linked in an appropriate and logical way that makes it easy to navigate from epic down to task and vice versa.
- [ ] All open issues are accounted for in a project board.
- [ ] Others TBD
